name: Deploy Polyglot Site
on:
  push:
    branches: [master]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Angular
        run: |
          cd angular-app
          npm install
          npx ng build --base-href ./

          
      - name: Build ReactVite
        run: |
          cd react-app
          npm install
          npm run build

          
      - name: Build VueVite
        run: |
          cd vue-app
          npm install
          npm run build
          
      - name: Assemble Final Site
        run: |
          mkdir -p final_dist/angular
          # 1. Copy everything from public into the root of the final folder
          cp -r public/* final_dist/
          # 2. Copy the Angular build into the /angular subfolder
          cp -r angular-app/dist/angular-app/browser/* final_dist/angular/
          cp -r react-app/dist/assets final_dist
          cp -r react-app/dist/index.html final_dist/react.html
          cp -r vue-app/dist/assets final_dist
          cp -r vue-app/dist/index.html final_dist/vue.html

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This must point to the folder containing your ROOT index.html
          path: final_dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4